// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

//
const TableNameHotel = "tb_hotel"

// Hotel mapped from table <tb_hotel>
type Hotel struct {
	ID        int64  `gorm:"column:id;primaryKey;comment:酒店id" json:"id"`                // 酒店id
	Name      string `gorm:"column:name;not null;comment:酒店名称" json:"name"`              // 酒店名称
	Address   string `gorm:"column:address;not null;comment:酒店地址" json:"address"`        // 酒店地址
	Price     int32  `gorm:"column:price;not null;comment:酒店价格" json:"price"`            // 酒店价格
	Score     int32  `gorm:"column:score;not null;comment:酒店评分" json:"score"`            // 酒店评分
	Brand     string `gorm:"column:brand;not null;comment:酒店品牌" json:"brand"`            // 酒店品牌
	City      string `gorm:"column:city;not null;comment:所在城市" json:"city"`              // 所在城市
	StarName  string `gorm:"column:star_name;comment:酒店星级，1星到5星，1钻到5钻" json:"star_name"` // 酒店星级，1星到5星，1钻到5钻
	Business  string `gorm:"column:business;comment:商圈" json:"business"`                 // 商圈
	Latitude  string `gorm:"column:latitude;not null;comment:纬度" json:"latitude"`        // 纬度
	Longitude string `gorm:"column:longitude;not null;comment:经度" json:"longitude"`      // 经度
	Pic       string `gorm:"column:pic;comment:酒店图片" json:"pic"`                         // 酒店图片
}

// TableName Hotel's table name 设置结构体对应的表名
func (*Hotel) TableName() string {
	return TableNameHotel
}
